### ISSUE TITLE
Version 4.0 Roadmap

### ISSUE THREAD

**Issue by UstymUkhman** [UstymUkhman/threejs-boilerplate#19]
### ~~Add Renderer Configs and GUI Controls:~~

  - [x] Tone Mapping and Exposure
  - [x] Custom Tone Mapping Shader
  - [x] Output Encoding
  
  ### ~~Assets Loader:~~

  - [x] Check and update loading events
  - [x] Test `publicFolder` option
  - [x] Restore and update unit tests

### ~~Event Emitter:~~

  - [x] Test multiple callbacks
  - [x] Restore and update unit tests

### ~~Unit Tests:~~

  - [x] Restore and update `Playground` & `GUIControls`
  - [x] Add new Renderer and GUI Controls configs
  - [x] Restore and update `Color` util
  - [x] Update `Worker` util
  
  ### ~~Misc.:~~
  
  - [x] Add assets folders in `src`
  - [x] Update version & coverage
  - [x] Update dependencies
